name: Build and collect modules
on:
  workflow_dispatch:
  push:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-modules:
    name: Check module existence
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.check_modules.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2
      - name: Check Modules
        id: check_modules
        run: |
          function check_module {
            echo $1
            if [ -d "./$1" ]; then
              if [ ! -z "$MODULES" ]; then
                MODULES="$MODULES, \"$1\""
              else
                MODULES="\"$1\""
              fi
            fi
          }
          
          MODULES=""
          
          check_module "bungeecord"
          check_module "velocity"
          check_module "spigot"
          check_module "paper"
          
          echo "matrix={\"module\":[$MODULES]}"
          echo "matrix={\"module\":[$MODULES]}" >> $GITHUB_OUTPUT

  build:
    name: Build and collect
    needs: check-modules
    if: needs.check-modules.outputs.matrix != '{"module":[]}'
    strategy:
      max-parallel: 1
      matrix: ${{ fromJSON(needs.check-modules.outputs.matrix) }}
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.1.0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew ${{ matrix.module }}:build
      - name: Collect
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ matrix.module }}
          path: ${{ matrix.module }}/build/libs/*${{ matrix.module }}.jar
